[workspace]
channels = ["conda-forge"]
name = "microscopy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pytorch = "2.4.*"
tensorflow-gpu = "2.17.*"
numpy = "*"
pandas = "*"
pillow = "*"


[system-requirements]
cuda = "12"

[pypi-dependencies]
cellpose = "*"
pillow-jxl-plugin = "*"
efficientnet = "*"
nvidia-cuda-nvcc-cu12="==12.5.82"