[workspace]
channels = ["conda-forge"]
name = "microscopy"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
pytorch = "2.7.*"
numpy = "2.1.*"
pandas = "*"
pillow = "*"

[system-requirements]
cuda = "12"

[pypi-dependencies]
cellpose = "==3.*"
pillow-jxl-plugin = "*"
efficientnet = "*"
nvidia-cuda-nvcc-cu12 = "==12.5.82"
nvidia-cusolver-cu12 = "==11.6.3.83"
tensorflow = "==2.19.0"
hdf5plugin = "*"