hail-batch:
    billing-project: 
    regions:
        - us-central1
    remote-tmpdir: gs://

cellpose:
    # docker image
    docker-image: us-central1-docker.pkg.dev/PROJECT/REPOSITORY/microscopy_computational_tools:latest
    machine-type: n1-standard-4+nvidia-tesla-t4+1
    num-processes: 4
    # although not mandatory, if you run cellpose, it is recommended to copy the following files
    # to a private bucket and provide the gs:// URI to this configuration file
    # https://www.cellpose.org/models/nucleitorch_0
    # https://www.cellpose.org/models/size_nucleitorch_0.npy
    model: null
    model-size: null

embedding:
    # docker image
    docker-image: us-central1-docker.pkg.dev/PROJECT/REPOSITORY/microscopy_computational_tools:latest
    machine-type: n1-standard-4+nvidia-tesla-t4+1
    num-workers: 4
    model-weights:
        # dino4cells, https://zenodo.org/records/8061392
        dino4cells: gs://.../DINO_cell_painting_base_checkpoint.pth
        # CellPainting-CNN, https://zenodo.org/records/7114558
        cpcnn: gs://.../Cell_Painting_CNN_v1.hdf5